--liquibase formatted sql

--changeset pchurzin:1

CREATE SEQUENCE restaurants_seq AS INTEGER START WITH 1000;

CREATE TABLE restaurants
(
    id INTEGER GENERATED BY DEFAULT AS SEQUENCE restaurants_seq PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);
